﻿USE Movies_P_421
--SELECT * FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE;
SELECT * FROM INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE;
SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS;

SELECT	COLUMN_NAME
FROM	INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE
WHERE	INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE.CONSTRAINT_NAME = 
(
SELECT	CONSTRAINT_NAME FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
WHERE	CONSTRAINT_TYPE=N'PRIMARY KEY' AND TABLE_NAME=N'Movies'
)